source 'http://rubygems.org'

gem 'rails', '~> 3.2.13'

gem 'rubytree', '0.7.0'

group :test do
  gem 'shoulda', '~> 2.10.3'
  gem 'edavis10-object_daddy', :require => 'object_daddy'
  gem 'mocha'

  platforms :mri_18 do gem 'ruby-debug' end
  platforms :mri_19 do gem 'ruby-debug19', :require => 'ruby-debug' end
end
#gem 'ruby-prof', :git => 'http://github.com/wycats/ruby-prof.git'

group :rmagick do
  #gem "rmagick", "~> 1.15.17"
  gem "rmagick", "~> 2.13.2"
end

# Use the commented pure ruby gems, if you have not the needed prerequisites on
# board to compile the native ones.  Note, that their use is discouraged, since
# their integration is propbably not that well tested and their are slower in
# orders of magnitude compared to their native counterparts. You have been
# warned.
#
platforms :mri do
  group :mysql do
    #gem "mysql"
    #gem "ruby-mysql"
  end

  group :mysql2 do
    gem "mysql2"#, '~> 0.2.7'
    gem "activerecord-mysql2-adapter"#, '0.0.2'
  end

  group :postgres do
    gem "pg", "~> 0.9.0", :require => 'pg'
    #gem "pg", "~> 0.11", :require => 'pg'
    #gem "pg", :require => 'pg'
    gem "postgres-pr"
  end
end

platforms :mri_18 do
  group :sqlite do
    gem "sqlite3-ruby", "< 1.3", :require => "sqlite3"
  end
end

platforms :mri_19 do
  group :sqlite do
    gem "sqlite3"
  end

group :test do
  gem 'test-unit'
  gem 'mocha'
  gem 'shoulda', '~> 2.10.3'
  gem 'object_daddy', :git => 'http://github.com/edavis10/object_daddy.git'
end

gem 'jquery-rails'

=begin
  group :mysql do
    gem "activerecord-jdbcmysql-adapter"
  end

  group :postgres do
    gem "activerecord-jdbcpostgresql-adapter"
  end

  group :sqlite do
    gem "activerecord-jdbcsqlite3-adapter"
  end
=end
end

# Load a "local" Gemfile
gemfile_local = File.join(File.dirname(__FILE__), "Gemfile.local")
if File.readable?(gemfile_local)
  puts "Loading #{gemfile_local} ..." if $DEBUG
  instance_eval(File.read(gemfile_local))
end

# Load plugins' Gemfiles
Dir.glob File.expand_path("../vendor/plugins/*/Gemfile", __FILE__) do |file|
  puts "Loading #{file} ..." if $DEBUG # `ruby -d` or `bundle -v`
  instance_eval File.read(file)
end

gem 'dispatcher'
gem 'oauth'

gem 'rake', '~> 10.0.4'
#gem 'meta_where'
gem 'ckeditor'
gem 'rails-ckeditor'
#gem 'paperclip'
gem 'tilt', "~> 1.4.1"

gem 'execjs'
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier', :git => 'git://github.com/lautis/uglifier.git'
  gem 'therubyracer'
end 

