source 'http://rubygems.org'

gem 'rails', '~> 4.0.0'
gem 'rubytree', '0.7.0'

#gem 'ruby-prof', :git => 'http://github.com/wycats/ruby-prof.git'

group :rmagick do
  #gem "rmagick", "~> 1.15.17"
  gem "rmagick", "~> 2.13.2"
end

gem "mysql2"
gem "pg", "~> 0.9.0", :require => 'pg'
gem "postgres-pr"
#gem "sqlite3"

group :test do
  gem 'test-unit'
  gem 'mocha'
  gem 'shoulda', '~> 2.10.3'
  #gem 'edavis10-object_daddy', :require => 'object_daddy'
  gem 'object_daddy', :git => 'http://github.com/edavis10/object_daddy.git'

  platforms :mri_18 do gem 'ruby-debug' end
  platforms :mri_19 do gem 'ruby-debug19', :require => 'ruby-debug' end
end

gem 'jquery-rails'

# Load a "local" Gemfile
gemfile_local = File.join(File.dirname(__FILE__), "Gemfile.local")
if File.readable?(gemfile_local)
  puts "Loading #{gemfile_local} ..." if $DEBUG
  instance_eval(File.read(gemfile_local))
end

# Load plugins' Gemfiles
Dir.glob File.expand_path("../vendor/plugins/*/Gemfile", __FILE__) do |file|
  puts "Loading #{file} ..." if $DEBUG # `ruby -d` or `bundle -v`
  instance_eval File.read(file)
end

gem 'dispatcher'
gem 'oauth'

gem 'rake', '~> 10.1.0'
#gem 'meta_where'
gem 'ckeditor'
gem 'rails-ckeditor'
#gem 'paperclip'
gem 'tilt', "~> 1.4.1"

gem 'execjs'
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier', :git => 'git://github.com/lautis/uglifier.git'
  gem 'therubyracer'
end 

