source 'https://rubygems.org'

gem 'rails', '~> 4.0.0'
gem 'rake', '~> 10.1.0'

gem 'rubytree', '0.7.0'
#gem 'ruby-prof', :git => 'http://github.com/wycats/ruby-prof.git'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem "mysql2", '0.3.12'
gem "pg", "~> 0.9.0", :require => 'pg'
gem "postgres-pr"

group :test do
  gem 'test-unit'
  gem 'mocha'
  gem 'shoulda', '~> 2.10.3'
  #gem 'edavis10-object_daddy', :require => 'object_daddy'
  gem 'object_daddy', :git => 'http://github.com/edavis10/object_daddy.git'

  platforms :mri_18 do gem 'ruby-debug' end
  platforms :mri_19 do gem 'ruby-debug19', :require => 'ruby-debug' end
end

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Load a "local" Gemfile
gemfile_local = File.join(File.dirname(__FILE__), "Gemfile.local")
if File.readable?(gemfile_local)
  puts "Loading #{gemfile_local} ..." if $DEBUG
  instance_eval(File.read(gemfile_local))
end

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'devise', branch: 'rails4'
#gem 'rails_admin', branch: 'rails-4'
#gem 'activeadmin', github: 'gregbell/active_admin'

group :development, :test do
  gem "visual_migrate", :git => "git://github.com/JironBach/visual_migrate.git"
  gem "minitest-rails"
end

group :test do
  #gem 'selenium-webdriver', '~> 2.35.1'
  #gem "zip-zip" and gem "rubyzip", "~> 1.0.0"
  #gem 'rubyzip', '< 1.0.0', :require => 'zip/zip'
  gem 'factory_girl'
  gem 'minitest-rails-capybara'
  gem 'minitest-colorize'
  gem 'minitest-focus'
end

